/**
 * Disclosure contract: a zone that is about to show, or is showing,
 * model-written content says so in the served HTML — to a machine
 * (JSON-LD with the IPTC digital source type, data-* on the zone root)
 * and to a person (a visible line of text).
 *
 * Server-rendered on purpose: the marking has to be in the HTML that
 * leaves the server, not added later by an effect that a crawler, a
 * reader with JS off, or the first paint never sees. Runs against the
 * BUILT package.
 */

import { test, expect } from 'vitest';
import React from 'react';
import { renderToString } from 'react-dom/server';
import {
  GenUIDisclosureNotice,
  GenUISection,
  GenUIZone,
  digitalSourceType,
  disclosureJsonLd,
  parseDisclosure,
} from 'genui-framework';

const ssr = (props: Record<string, unknown> = {}) =>
  renderToString(
    React.createElement(GenUIZone, {
      apiUrl: 'http://backend.test',
      zoneId: 'ssr-zone',
      ...props,
    } as any)
  );

test('server-rendered markup carries the machine-readable marking', () => {
  const html = ssr();
  expect(html).toContain('application/ld+json');
  expect(html).toContain(
    'https://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'
  );
  expect(html).toContain('data-ai-generated="true"');
  expect(html).toContain('data-ai-provenance="generated"');
});

test('server-rendered markup carries the visible notice', () => {
  expect(ssr()).toContain('AI-generated content');
});

test('the host sets the wording and the position', () => {
  const html = ssr({
    disclosure: { text: 'Contenuto generato con AI', position: 'below-right' },
  });
  expect(html).toContain('Contenuto generato con AI');
  expect(html).not.toContain('AI-generated content');
});

test('disclosure={false} drops the notice but keeps the markup', () => {
  const html = ssr({ disclosure: false });
  expect(html).not.toContain('AI-generated content');
  expect(html).toContain('application/ld+json');
});

test('a zone that will never load is not marked', () => {
  expect(ssr({ loadOnMount: false })).toBe('');
});

test('the notice is usable outside a zone, with the same class and tokens', () => {
  const html = renderToString(
    React.createElement(GenUIDisclosureNotice, { text: 'Generated by AI' })
  );
  expect(html).toContain('genui-zone__disclosure');
  expect(html).toContain('Generated by AI');
  // Default wording when the host sets none
  expect(renderToString(React.createElement(GenUIDisclosureNotice))).toContain(
    'AI-generated content'
  );
});

test('the theme carries the notice config for a whole tenant', () => {
  const theme = {
    disclosureText: 'Contenuto generato con AI',
    disclosurePosition: 'below-center' as const,
    disclosureFontSize: '13px',
    disclosureOpacity: '0.8',
  };
  const html = ssr({ theme });
  expect(html).toContain('Contenuto generato con AI');
  // The two visual knobs become CSS custom properties; wording,
  // position and on/off never reach a stylesheet
  expect(html).toContain('--genui-disclosure-font-size:13px');
  expect(html).toContain('--genui-disclosure-opacity:0.8');
  expect(html).not.toContain('--genui-disclosure-text');

  // A theme that turns it off hides the notice, keeps the markup
  const off = ssr({ theme: { ...theme, disclosureEnabled: 'off' as const } });
  expect(off).not.toContain('Contenuto generato con AI');
  expect(off).toContain('application/ld+json');

  // An explicit prop is the more specific statement and wins
  const overridden = ssr({
    theme: { ...theme, disclosureEnabled: 'off' as const },
    disclosure: { text: 'Zone wording' },
  });
  expect(overridden).toContain('Zone wording');
});

test('the six placements put the notice where they say', () => {
  // The class carries side and alignment; DOM order follows visual
  // order, so the notice is announced where it is seen
  for (const [position, first] of [
    ['above-left', true],
    ['above-center', true],
    ['above-right', true],
    ['below-left', false],
    ['below-center', false],
    ['below-right', false],
  ] as const) {
    const html = ssr({ disclosure: { position, text: 'MARK' } });
    expect(html).toContain(`genui-zone__disclosure--${position}`);
    const noticeAt = html.indexOf('MARK');
    const contentAt = html.indexOf('genui-zone-skeleton');
    expect(noticeAt < contentAt).toBe(first);
  }
});

test('a section emits no disclosure vars when the theme sets none', () => {
  const html = renderToString(
    React.createElement(GenUISection, { theme: { accentColor: '#ff0055' } })
  );
  expect(html).not.toContain('--genui-disclosure');
});

test('provenance maps to the IPTC vocabulary, never to an invented term', () => {
  expect(digitalSourceType('generated')).toContain('trainedAlgorithmicMedia');
  expect(digitalSourceType('verbatim-from-input')).toContain(
    'compositeWithTrainedAlgorithmicMedia'
  );
  expect(digitalSourceType('not-generated')).toContain('algorithmicMedia');
});

test('json-ld cannot be closed by the content it describes', () => {
  const json = disclosureJsonLd(
    { aiGenerated: true, provenance: 'generated' },
    '</script><img onerror=alert(1)>'
  );
  expect(json).not.toContain('</script>');
  expect(json).toContain('\\u003c/script');
});

test('an unreadable backend block reads as fully generated', () => {
  expect(parseDisclosure(undefined)).toBeUndefined();
  expect(parseDisclosure({ provenance: 'verbatim-from-input' })).toEqual({
    aiGenerated: true,
    provenance: 'verbatim-from-input',
    generatedAt: undefined,
    system: undefined,
    model: undefined,
  });
  expect(parseDisclosure({ ai_generated: false })?.provenance).toBe(
    'not-generated'
  );
});
