/**
 * GenUI Component Registry
 *
 * Lets the host app extend the component vocabulary with its own design
 * system: register a React component under a type name, describe its
 * data schema to the backend (customComponents prop / option), and the
 * LLM can generate it like any built-in type.
 *
 *   // 1. Render side: name -> React component
 *   registerGenUIComponent('hero_banner', HeroBanner);
 *
 *   // 2. Generation side: name -> JSON schema (+ description)
 *   <GenUIZone
 *     customComponents={[{
 *       name: 'hero_banner',
 *       description: 'Full-width hero with headline and CTA',
 *       dataSchema: {
 *         type: 'object',
 *         required: ['headline'],
 *         properties: {
 *           headline: { type: 'string' },
 *           subtitle: { type: 'string' },
 *           cta_label: { type: 'string' },
 *           cta_url: { type: 'string' },
 *         },
 *       },
 *     }]}
 *     ...
 *   />
 *
 * The backend validates generated data against the JSON schema and
 * applies the URL whitelist before it ever reaches the renderer.
 */

import type React from 'react';

export interface GenUIRegisteredComponentProps {
  /** Validated, sanitized data payload generated by the backend */
  data: any;
  /** Optional layout hints emitted by the LLM */
  layout?: Record<string, unknown>;
}

export type GenUIRegisteredComponent =
  React.ComponentType<GenUIRegisteredComponentProps>;

/** Definition sent to the backend so the LLM knows the component exists. */
export interface GenUICustomComponentDef {
  /** Type name: lowercase, 2-32 chars, [a-z0-9_-], starts with a letter */
  name: string;
  /** JSON Schema of the component's data payload */
  dataSchema: Record<string, unknown>;
  /** One-liner telling the LLM when to use this component */
  description?: string;
  /** Optional example data payload shown to the LLM */
  example?: Record<string, unknown>;
}

const BUILTIN_TYPES = ['bento', 'chart', 'text', 'buttons'];
const NAME_PATTERN = /^[a-z][a-z0-9_-]{1,31}$/;

const registry = new Map<string, GenUIRegisteredComponent>();

/**
 * Register a React component for a custom type name.
 * Returns an unregister function.
 */
export const registerGenUIComponent = (
  name: string,
  component: GenUIRegisteredComponent,
): (() => void) => {
  if (!NAME_PATTERN.test(name)) {
    throw new Error(
      `Invalid GenUI component name "${name}": use 2-32 chars, lowercase ` +
      `letters, digits, "_" or "-", starting with a letter`,
    );
  }
  if (BUILTIN_TYPES.includes(name)) {
    throw new Error(`GenUI component "${name}" is built-in and cannot be overridden`);
  }
  if (registry.has(name)) {
    console.warn(`GenUI component "${name}" re-registered`);
  }
  registry.set(name, component);
  return () => {
    if (registry.get(name) === component) {
      registry.delete(name);
    }
  };
};

/** Look up a registered component (undefined when unknown). */
export const getRegisteredGenUIComponent = (
  name: string,
): GenUIRegisteredComponent | undefined => registry.get(name);

/** Names of all registered custom components. */
export const getRegisteredGenUIComponentNames = (): string[] =>
  Array.from(registry.keys());
