/**
 * GenUI Component Registry
 *
 * Lets the host app extend the component vocabulary with its own design
 * system: register a React component under a type name, describe its
 * data schema to the backend (customComponents prop / option), and the
 * LLM can generate it like any built-in type.
 *
 *   // 1. Render side: name -> React component
 *   registerGenUIComponent('hero_banner', HeroBanner);
 *
 *   // 2. Generation side: name -> JSON schema (+ description)
 *   <GenUIZone
 *     customComponents={[{
 *       name: 'hero_banner',
 *       description: 'Full-width hero with headline and CTA',
 *       dataSchema: {
 *         type: 'object',
 *         required: ['headline'],
 *         properties: {
 *           headline: { type: 'string' },
 *           subtitle: { type: 'string' },
 *           cta_label: { type: 'string' },
 *           cta_url: { type: 'string' },
 *         },
 *       },
 *     }]}
 *     ...
 *   />
 *
 * The backend validates generated data against the JSON schema and
 * applies the URL whitelist before it ever reaches the renderer.
 */

import type React from "react";

export interface GenUIRegisteredComponentProps {
  /** Validated, sanitized data payload generated by the backend */
  data: any;
  /** Optional layout hints emitted by the LLM */
  layout?: Record<string, unknown>;
}

export type GenUIRegisteredComponent =
  React.ComponentType<GenUIRegisteredComponentProps>;

/** Definition sent to the backend so the LLM knows the component exists. */
export interface GenUICustomComponentDef {
  /** Type name: lowercase, 2-32 chars, [a-z0-9_-], starts with a letter */
  name: string;
  /** JSON Schema of the component's data payload */
  dataSchema: Record<string, unknown>;
  /** One-liner telling the LLM when to use this component */
  description?: string;
  /** Optional example data payload shown to the LLM */
  example?: Record<string, unknown>;
}

/**
 * Types the framework renders itself.
 *
 * You may register your own component under one of these names to replace the built-in rendering (see registerGenUIComponent).
 */
export const BUILTIN_TYPES: readonly string[] = [
  "bento",
  "chart",
  "text",
  "buttons",
  "tabs_feature",
  "steps_section",
  "stats_banner",
  "testimonial_carousel",
  "pricing_cards",
  "content_grid",
  "hero_banner",
  "case_studies",
  "quote",
  "logo_wall",
];
const NAME_PATTERN = /^[a-z][a-z0-9_-]{1,31}$/;

const registry = new Map<string, GenUIRegisteredComponent>();

/**
 * Register a React component for a type name.
 * Returns an unregister function.
 *
 * Two uses, same call:
 * - a custom name (`acme_offer_card`) teaches the renderer a type the host
 *   also declares to the backend via `customComponents` / `custom_components`
 * - a built-in name (`hero_banner`) replaces the framework's own rendering of
 *   that type, keeping the schema and the prompt vocabulary it already has
 *
 * A registration always wins over the built-in component of the same name.
 */
export const registerGenUIComponent = (
  name: string,
  component: GenUIRegisteredComponent,
): (() => void) => {
  if (!NAME_PATTERN.test(name)) {
    throw new Error(
      `Invalid GenUI component name "${name}": use 2-32 chars, lowercase ` +
        `letters, digits, "_" or "-", starting with a letter`,
    );
  }
  if (registry.has(name)) {
    console.warn(`GenUI component "${name}" re-registered`);
  }
  registry.set(name, component);
  return () => {
    if (registry.get(name) === component) {
      registry.delete(name);
    }
  };
};

/** Look up a registered component (undefined when unknown). */
export const getRegisteredGenUIComponent = (
  name: string,
): GenUIRegisteredComponent | undefined => registry.get(name);

/** Names of all registered custom components. */
export const getRegisteredGenUIComponentNames = (): string[] =>
  Array.from(registry.keys());
