/**
 * The error the hooks hand to `onError` and `errorComponent`.
 *
 * `status` is the HTTP status, or the one the stream reported in its `error` event.
 * `retryAfter` (seconds) is set when the backend said the absence is temporary: a zone still being generated by another request, or an authoritative store out of reach.
 * The library never retries on its own; what to show meanwhile is the host's call.
 */
export class GenUIError extends Error {
  readonly status?: number;
  readonly retryAfter?: number;

  constructor(message: string, status?: number, retryAfter?: number) {
    super(message);
    this.name = 'GenUIError';
    this.status = status;
    this.retryAfter = retryAfter;
  }
}

/** A network failure or a thrown value becomes a GenUIError without a status */
export const asGenUIError = (err: unknown): GenUIError =>
  err instanceof GenUIError
    ? err
    : new GenUIError(err instanceof Error ? err.message : String(err));

/** Retry-After in seconds, from either the delta-seconds or the HTTP-date form */
export const parseRetryAfter = (value: unknown): number | undefined => {
  if (value == null || value === '') return undefined;
  const text = String(value).trim();
  if (/^\d+$/.test(text)) return Number(text);
  const at = Date.parse(text);
  return Number.isNaN(at) ? undefined : Math.max(0, Math.ceil((at - Date.now()) / 1000));
};

/**
 * Error for a non-ok response.
 * Retry-After is a header, which a cross-origin page can read only when the backend lists it in Access-Control-Expose-Headers.
 */
export const errorFromResponse = async (
  response: Response,
  fallback: string,
): Promise<GenUIError> => {
  const body = await response.json().catch(() => ({}));
  return new GenUIError(
    typeof body?.detail === 'string' ? body.detail : `${fallback}: ${response.status}`,
    response.status,
    parseRetryAfter(response.headers?.get('Retry-After')),
  );
};
